### ISSUE TITLE
un-fake-ify the existing presences table to use real library IDs from Georgia

### ISSUE THREAD

**Issue by sknep** [IMLS/estimating-wifi#249]
something something update migration :)

**Comment by jadudm** [comment]
To add to the som'in-som'in:

The existing data in the system was pulled from *real* data, but we faked the library IDs in an abundance of caution. So, what would have been a valid identifier (e.g. GA0026-001) became AA0001-001.

This was fine, until it wasn't. Because we pulled in IMLS metadata for use in the interface, we now need real IDs so we can test the lookups. So, we're going to add a migration that rewrites the fake IDs (e.g. AA0001-001) to a real ID (e.g. GA0028-001). There is a huge caveat here, however: although we are using real IDs, the data is *not* from those libraries.

Because we're using this data for testing and development purposes, this seems fine.
