### ISSUE TITLE
Update API tests

### ISSUE THREAD

**Issue by anagradova** [IMLS/estimating-wifi#285]
### Description

Updates need to be made to the testing scripts for the API endpoints that were recently added and an end-to-end test of the api for the presence table needs to be performed.

## Anonymous API endpoints

- [x] #308
- [x] #310

## Authenticated API endpoints

- [x] Add tests for /rpc/beat_the_heart
- [x] Add tests for /rpc/update_presences

**Comment by jadudm** [comment]
I'm going to close this ticket. Work has been done in the past 1.5w to significantly increase coverage of the API via Python-based unit tests.

However:

1. No new endpoints should be created without unit tests. Those should be failure tests, success tests, etc. making sure that the API responds appropriately in multiple ways. That should be acceptance criteria on every feature, not something that requires it's own ticket.
2. We need a ticket for end-to-end testing, because that is very different than API unit-tests.
