### ISSUE TITLE
Write up ADR for front-end stack

### ISSUE THREAD

**Issue by jreme100** [IMLS/estimating-wifi#85]

**Comment by wesley-dean-gsa** [comment]
what does this mean?  what are the objective criteria for "easily maintained?"

**Comment by sknep** [comment]
I wonder if this would be best served by documenting the front end tech stack choices in an ADR. Would that be welcome/useful? In brief, we've selected:
- a Vue3 JS app for it's beginner-friendly docs and simple learning curve, while having been around long enough to have significant community support and tooling, also because it has built-in router and state management
- built using vitest because it's fast/performant and had works-out-of-the-box unit testing (compared to Jest and Cypress, which were also tested)
- using ChartJS for dynamic graph generation -- while not the "new shiny", it's simpler to learn and use than something like D3, which admittedly is more capable of complex graphs but harder to use (and we might not need much more than bar charts anyways)
- USWDS is imported in a way that consumes the most up-to-date SCSS and JS, but the component markup can be customized in the app source as needed. So that allows for fine-tuning and more efficient data binding.
- We have linting for ease of editing between different contributors, but we didn't choose typescript so as to keep the barrier to entry for editing low (given that we can anticipate little about the likely development experience of the community contributors in the future)

Stuff like that? @cantsin do those feel defensible to you?

**Comment by cantsin** [comment]
@sknep absolutely. All of these are excellent points and should probably be in an ADR for posterity, yes. I'm wondering if we want to separate choosing Vue and USWDS into two ADRs?

I think we can literally copy and paste the above and put in an ADR (or two) without too much fuss, let's not overdo it?

**Comment by jadudm** [comment]
Agreed. I wouldn't worry about separating them out, even. A later ADR can always change things, and the combo nature of this won't hurt anything.

Perfect is the enemy of done. I think, as articulated in this thread, it's 90% of the way to an ADR. The other 10% is formatting around it.
